### ISSUE TITLE
Null name or login during search

### ISSUE THREAD

**Issue by GroovinChip** [GroovinChip/GitHub-Activity-Feed#91]
Search can sometimes return a user with a null `login` or `name`.

Stack trace:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building UserInfoRow(dirty):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 378 pos 10: 'data != null'

The relevant error-causing widget was: 
  UserInfoRow file:///Users/groov/development/flutter_projects/apps/GitHub-Activity-Feed/lib/widgets/user_widgets/user_tile.dart:26:14
When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:378:10)
#3      UserInfoRow.build (package:github_activity_feed/widgets/user_widgets/user_tile.dart:86:15)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4755:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4375:5)
...
====================================================================================================
```

Code in question:
```dart
Text(
  user.name ?? user.login,
  style: TextStyle(
    fontWeight: FontWeight.bold,
    fontSize: 16,
  ),
),
```

**Comment by GroovinChip** [comment]
Fixed in version 0.5.4
